### ISSUE TITLE
Overview / Inspiration Page

### ISSUE THREAD

**Issue by ninagw** [ninagw/book-journal-app#1]

**Comment by ninagw** [comment]
## Value proposition
**As a** book enthusiast
**I want to** a book overview page 
**In order to** discover new books.

## Description
![Image](https://github.com/ninagw/book-journal-app/assets/150810914/09c17e0b-fd50-46c7-b446-52dd4a61bf4b)

## Acceptance criteria
- overview page with book covers 
- scrollable 
- should be centered
- design must be responsive 

## Tasks
- [ ] Create a data.json that contains book data
- [ ] Create the component 'BookList' and map through the book data to render the book cover for each book
- [ ] index.js: render a h1 element for the app name
- [ ] index.js: render the 'BookList' component
