### ISSUE TITLE
Add SearchBar | index.js

### ISSUE THREAD

**Issue by ninagw** [ninagw/book-journal-app#4]

**Comment by ninagw** [comment]
## Value proposition
**As a** book enthusiast
**I want to** be able to filter the books on the overview page (ex. genre, title,...)
**In order to** discover new books in my favorite genre.

## Description
![Image](https://github.com/ninagw/book-journal-app/assets/150810914/2f5850eb-bac9-4943-be51-9544b38093d5)


## Acceptance criteria
- by choosing a genre or typing a title the overview page should show the chosen books

## Tasks
- [x] Create a new branch feature/search-bar
- [x] Create component 'SearchBar' 
- [x] index.js: render the 'SearchBar' component
